name: template_tests
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    if: github.event.repository.name != 'python_package_template'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Readme
      run: |
        md5=($(md5sum README.md))
        if [[ $md5 == "e43bdc6101d8da7596dc125475e07c77" ]] ;then
          echo ${{ github.event.repository.name }}
          echo 'Your readme still is in default template state, you should change it!'
          exit 1
        fi
    - name: Check setup.py
      run: |
        md5=($(md5sum setup.py))
        if [[ $md5 == "d2a7ad1ed35d94704846fce235b8dffd" ]] ;then
          echo 'Your setup.py still is in default template state, you should change it!'
          exit 1
        fi
    - name: Check package_rename
      run: |
        dir="src/package_name"
        if [[ -d "$dir" ]] ;then
          echo 'You did not change the name of your package, you  should change it!'
          exit 1
        fi
    - name: Check tox.ini
      run: |
        md5=($(md5sum tox.ini))
        if [[ $md5 == "3099903589b629929c0e465e78725724" ]] ;then
          echo 'You need to change the package-name referenced in tox.ini on line 32!'
          exit 1
        fi
    - name: Check test_name
      run: |
        file="tests/test_module_name.py"
        if [[ -f "$file" ]] ;then
          echo 'You did not change the name of your test, you  should change it!'
          exit 1
        fi
    - name: Remove this action
      run: |
        echo 'You have not removed this GitHub action - I strongly recommend you to!'
        exit 1
